[build]
  command = "npm run build"
  publish = "/build"
  base = "/"
[build]
  command = "npm run develop"
  publish = "/build"
  base = "/strapi"
[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200